version: '3.9'

services:
  drupal:
    ports:
      - "80:80"
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-sites:/var/www/html/sites
      - drupal-themes:/var/www/html/themes
  
  postgres:
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/psql-demo-password
    secrets:
      - psql-demo-password
    volumes:
      - drupal-data:/var/lib/postgresql/data

volumes:
  drupal-data:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes:

# The test environment uses a local file for secrets (file: ./psql-demo-password.txt)
# The production environment expects secrets to be managed externally (external: true)
secrets:
  psql-demo-password:
    external: true
